-- Create rescues table for ADCH members
CREATE TABLE public.rescues (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL DEFAULT 'Full',
  region TEXT NOT NULL,
  website TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.rescues ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Rescues are publicly viewable"
ON public.rescues
FOR SELECT
USING (true);

-- Add foreign key to dogs table
ALTER TABLE public.dogs 
ADD COLUMN rescue_id UUID REFERENCES public.rescues(id);

-- Insert ADCH member rescues (dog-related ones)
INSERT INTO public.rescues (name, type, region, website) VALUES
('Aireworth Dogs in Need', 'Full', 'Yorkshire & The Humber', 'www.areworthdogsinneed.co.uk'),
('Akita Rescue & Welfare Trust (UK)', 'Full', 'South East England', 'www.akitarescue.org.uk'),
('All Creatures Great & Small', 'Full', 'South Wales', 'www.allcreaturesgreatandsmall.org.uk'),
('All Dogs Matter', 'Full', 'London', 'www.alldogsmatter.co.uk'),
('Animal Care - Lancaster, Morecambe & District', 'Full', 'North West England', 'www.animalcare-lancaster.co.uk'),
('Animal Concern Cumbria', 'Full', 'North West England', 'www.animalconcerncumbria.org'),
('Animal Rescue Cumbria', 'Full', 'North West England', 'www.animalrescuecumbria.co.uk'),
('Animal Support Angels', 'Full', 'East England', 'www.animalsupportangels.com'),
('Animal Welfare Furness', 'Full', 'North West England', 'www.animals-in-need.org'),
('Animals in Need Northants', 'Full', 'East Midlands', 'www.animalsinneed.uk'),
('Ashbourne Animal Welfare', 'Full', 'East Midlands', 'www.ashbourneanimalwelfare.org'),
('Balto''s Dog Rescue', 'Full', 'National', 'www.baltosdogrescue.uk'),
('Bath Cats and Dogs Home', 'Full', 'South West England', 'www.bcdh.org.uk'),
('Battersea', 'Full', 'London', 'www.battersea.org.uk'),
('Benvardin Animal Rescue Kennels', 'Full', 'Northern Ireland', 'www.benvardinkennels.com'),
('Berwick Animal Rescue Kennels', 'Full', 'North East England', 'www.b-a-r-k.co.uk'),
('Birmingham Dogs Home', 'Full', 'West Midlands', 'www.birminghamdogshome.org.uk'),
('Bleakholt Animal Sanctuary', 'Full', 'North West England', 'www.bleakholt.org'),
('Blue Cross', 'Full', 'National', 'www.bluecross.org.uk'),
('Border Collie Trust GB', 'Full', 'West Midlands', 'www.bordercollietrust.org.uk'),
('Borders Pet Rescue', 'Full', 'Scottish Borders', 'www.borderspetrescue.org'),
('Boxer Welfare Scotland', 'Full', 'Aberdeen & Grampian', 'www.boxerwelfarescotland.org.uk'),
('Bristol Animal Rescue Centre', 'Full', 'South West England', 'www.bristolarc.org.uk'),
('Bristol Dog Action Welfare Group', 'Full', 'South West England', 'www.dawg.org.uk'),
('Bulldog Rescue & Re-homing Trust', 'Full', 'South East England', 'www.bulldogrescue.co.uk'),
('Carla Lane Animals In Need', 'Full', 'North West England', 'www.carlalaneanimalsinneed.co.uk'),
('Causeway Coast Dog Rescue', 'Full', 'Northern Ireland', 'www.causewaycoastdogrescue.org'),
('Cheltenham Animal Shelter', 'Full', 'South West England', 'www.gawa.org.uk'),
('Chilterns Dog Rescue Society', 'Full', 'East England', 'www.chilternsdogrescue.org.uk'),
('Dog Aid Society Scotland', 'Full', 'Scotland', 'www.dogaidsociety.com'),
('Dogs Trust', 'Full', 'National', 'www.dogstrust.org.uk'),
('Dogs Trust Ireland', 'Full', 'Ireland', 'www.dogstrust.ie'),
('Dumfries & Galloway Canine Rescue Centre', 'Full', 'Dumfries & Galloway', 'www.caninerescue.co.uk'),
('Durham Dogs and Cats Home', 'Full', 'North East England', 'www.durhamdogsandcats.uk'),
('Eden Animal Rescue', 'Full', 'North West England', 'www.edenanimalrescue.org.uk'),
('Edinburgh Dog & Cat Home', 'Full', 'Edinburgh & the Lothians', 'www.edch.org.uk'),
('Fen Bank Greyhound Sanctuary', 'Full', 'East England', 'www.fenbankgreyhounds.co.uk'),
('Ferne Animal Sanctuary', 'Full', 'South West England', 'www.ferneanimalsanctuary.org'),
('Foal Farm Animal Rescue', 'Full', 'South East England', 'www.foalfarm.org.uk'),
('Forest Dog Rescue', 'Full', 'West Midlands', 'www.forest-dog-rescue.org.uk'),
('Forever Hounds Trust', 'Full', 'South East England', 'www.foreverhoundstrust.org'),
('Freshfields Animal Rescue', 'Full', 'North West England', 'www.freshfields.org.uk'),
('Friends of Akitas Trust UK', 'Full', 'East Midlands', 'www.friendsofakitas.co.uk'),
('Gables Dogs & Cats Home', 'Full', 'South West England', 'www.gablesfarm.org.uk'),
('Garbos German Shepherd Dog Rescue', 'Full', 'South East England', 'www.garbosgsdrescue.co.uk'),
('German Shepherd Rescue Elite', 'Full', 'South East England', 'www.gsrelite.co.uk'),
('German Shepherd Rescue South', 'Full', 'South East England', 'www.german-shepherd-rescue-hampshire.org.uk'),
('German Shorthaired Pointer Rescue UK', 'Full', 'South Wales', 'www.gsprescue-uk.org.uk'),
('Greenacres Rescue', 'Full', 'South Wales', 'www.greenacresrescue.org.uk'),
('Greyhound Gap', 'Full', 'West Midlands', 'www.greyhoundgap.org.uk'),
('Greyhound Rescue Wales', 'Full', 'Mid Wales', 'www.greyhoundrescuewales.co.uk'),
('Greyhound Trust', 'Full', 'South East England', 'www.greyhoundtrust.org.uk'),
('Greyhound Welfare South Wales', 'Full', 'South Wales', 'www.facebook.com/GreyhoundWelfareSouthWales'),
('Grovehill Animal Trust', 'Full', 'Northern Ireland', 'www.grovehillanimaltrust.org'),
('Happy Landings Animal Shelter', 'Full', 'South West England', 'www.happy-landings.org.uk'),
('Happy Staffie Rescue', 'Full', 'West Midlands', 'www.happystaffie.co.uk'),
('Holly Hedge Animal Sanctuary', 'Full', 'South West England', 'www.hollyhedge.org.uk'),
('Hope Rescue', 'Full', 'South Wales', 'www.hoperescue.org.uk'),
('Jerry Green Dog Rescue', 'Full', 'East Midlands', 'www.jerrygreendogs.org.uk'),
('Just Springers Rescue', 'Full', 'South East England', 'www.justspringersrescue.co.uk'),
('K9 Focus', 'Full', 'South West England', 'www.k9focus.co.uk'),
('Keith''s Rescue Dogs', 'Full', 'East Midlands', 'www.keithsrescuedogs.co.uk'),
('Labrador Lifeline Trust', 'Full', 'South East England', 'www.labrador-lifeline.com'),
('Labrador Rescue Trust', 'Full', 'South West England', 'www.labrador-rescue.com'),
('Last Chance Animal Rescue', 'Full', 'South East England', 'www.lastchanceanimalrescue.co.uk'),
('Leicester Animal Aid', 'Full', 'East Midlands', 'www.leicesteranimalaid.org.uk'),
('Lord Whisky Sanctuary Fund', 'Full', 'South East England', 'www.lordwhisky.co.uk'),
('MADRA', 'Full', 'Ireland', 'www.madra.ie'),
('Manchester & District Home For Lost Dogs', 'Full', 'North West England', 'www.dogshome.net'),
('Margaret Green Animal Rescue', 'Full', 'South West England', 'www.margaretgreenanimalrescue.org.uk'),
('Maxi''s Mates', 'Full', 'Yorkshire & The Humber', 'www.maxismates.org.uk'),
('Mayflower Sanctuary', 'Full', 'Yorkshire & The Humber', 'www.mayflowersanctuary.co.uk'),
('Mayhew Animal Home', 'Full', 'London', 'www.themayhew.org'),
('Mid Antrim Animal Sanctuary', 'Full', 'Northern Ireland', 'www.midantrim.org'),
('Mrs Murrays Home for Stray Dogs and Cats', 'Full', 'Aberdeen & Grampian', 'www.mrsmurrays.co.uk'),
('National Animal Welfare Trust', 'Full', 'National', 'www.nawt.org.uk'),
('Newcastle Dog & Cat Shelter', 'Full', 'North East England', 'www.dogandcatshelter.com'),
('North Clwyd Animal Rescue', 'Full', 'North Wales', 'www.ncar.org.uk'),
('Oak Tree Animals'' Charity', 'Full', 'North West England', 'www.oaktreeanimals.org.uk'),
('Oldies Club', 'Full', 'National', 'www.oldies.org.uk'),
('Pawprints Dog Rescue', 'Full', 'West Midlands', 'www.pawprintsdogrescue.org'),
('PAWS Animal Rescue', 'Full', 'Ireland', 'www.paws.ie'),
('People for Animal Care Trust', 'Full', 'East England', 'www.pactsanctuary.org'),
('Pro Dogs Direct', 'Full', 'South East England', 'www.prodogsdirect.org.uk'),
('Rain Rescue', 'Full', 'Yorkshire & The Humber', 'www.rainrescue.co.uk'),
('Rainbow Rescue', 'Full', 'Northern Ireland', 'www.rainbowrehoming.com'),
('Raystede Centre for Animal Welfare', 'Full', 'South East England', 'www.raystede.org'),
('Rescue Me Animal Sanctuary', 'Full', 'North West England', 'www.rescueme.org.uk'),
('Rosie''s Trust', 'Full', 'Northern Ireland', 'www.rosiestrust.org'),
('Rottweiler Welfare Association', 'Full', 'West Midlands', 'www.rottweilerwelfare.co.uk'),
('RSPCA', 'Full', 'National', 'www.rspca.org.uk'),
('Saints Sled Dog Rescue', 'Full', 'National', 'www.saintssleddogrescue.co.uk'),
('Saving Saints Rescue UK', 'Full', 'North West England', 'www.savingsaintsrescue.co.uk'),
('Scottish SPCA', 'Full', 'Scotland', 'www.scottishspca.org'),
('Staffie Rescue Scotland', 'Full', 'Aberdeen & Grampian', 'www.staffierescuescotland.co.uk'),
('Second Chance Akita Rescue', 'Full', 'West Midlands', 'www.secondchanceakitarescue.co.uk'),
('Senior Staffy Club', 'Full', 'West Midlands', 'www.seniorstaffyclub.co.uk'),
('Society for Abandoned Animals', 'Full', 'North West England', 'www.saarescue.co.uk'),
('Southern Golden Retriever Rescue', 'Full', 'South England', 'www.sgrr.org.uk'),
('Spaniel Aid', 'Full', 'National', 'www.spanielaid.co.uk'),
('Spirit of the Dog Rescue', 'Full', 'East England', 'www.spiritofthedog.uk'),
('Sprocker Assist and Rescue', 'Full', 'National', 'www.sprockerassist.org'),
('St Francis Dogs Home', 'Full', 'South West England', 'www.stfrancisnewquay.org.uk'),
('Staffie and Stray Rescue', 'Full', 'South West England', 'www.staffieandstray.co.uk'),
('Stokenchurch Dog Rescue', 'Full', 'South East England', 'www.stokenchurchdogrescue.org.uk'),
('Tails Animal Welfare', 'Full', 'North West England', 'www.tailsanimalwelfare.com'),
('Team Poundie', 'Full', 'North East England', 'www.teampoundie.com'),
('Teckels Animal Sanctuaries', 'Full', 'South West England', 'www.teckelsanimalsanctuaries.co.uk'),
('The Animal House Rescue', 'Full', 'West Midlands', 'www.theanimalhouserescue.co.uk'),
('Thornberry Animal Sanctuary', 'Full', 'Yorkshire & The Humber', 'www.thornberryanimalsanctuary.org'),
('Three Counties Dog Rescue', 'Full', 'East Midlands', 'www.threecountiesdogrescue.org'),
('UK Spaniel Rescue', 'Full', 'National', 'www.ukspanielrescue.co.uk'),
('USPCA', 'Full', 'Northern Ireland', 'www.uspca.co.uk'),
('Wadars Animal Rescue', 'Full', 'South East England', 'www.wadars.co.uk'),
('Warrington Animal Welfare', 'Full', 'North West England', 'www.warringtonanimalwelfare.org.uk'),
('West Yorkshire Dog Rescue', 'Full', 'Yorkshire & The Humber', 'www.westyorkshiredogrescue.co.uk'),
('Wirral Animal Welfare Association', 'Full', 'North West England', 'www.wirralanimalwelfare.com'),
('Woodgreen Pets Charity', 'Full', 'East England', 'www.woodgreen.org.uk'),
('Woodlands Animal Sanctuary', 'Full', 'North West England', 'www.woodlandsanimalsanctuary.org.uk'),
('Worcestershire Animal Rescue Shelter', 'Full', 'West Midlands', 'www.wars.org.uk'),
('Wythall Animal Sanctuary', 'Full', 'West Midlands', 'www.wythallanimalsanctuary.org');

-- Update existing dogs to link to rescues
UPDATE public.dogs SET rescue_id = (SELECT id FROM public.rescues WHERE name = 'Battersea' LIMIT 1) WHERE rescue = 'Battersea Dogs Home';
UPDATE public.dogs SET rescue_id = (SELECT id FROM public.rescues WHERE name = 'Dogs Trust' LIMIT 1) WHERE rescue = 'Dogs Trust Manchester';
UPDATE public.dogs SET rescue_id = (SELECT id FROM public.rescues WHERE name = 'Bristol Animal Rescue Centre' LIMIT 1) WHERE rescue = 'Bristol Animal Rescue';
UPDATE public.dogs SET rescue_id = (SELECT id FROM public.rescues WHERE name = 'Birmingham Dogs Home' LIMIT 1) WHERE rescue = 'Birmingham Dogs Home';
UPDATE public.dogs SET rescue_id = (SELECT id FROM public.rescues WHERE name = 'Scottish SPCA' LIMIT 1) WHERE rescue = 'Scottish SPCA';