-- Add missing quality rescue organizations
-- These are dog-related rescues from quality organizations committed to high animal welfare standards

INSERT INTO dogadopt.rescues (name, type, region, website)
VALUES
  ('Animals in Need Northants', 'Full', 'East Midlands', 'www.animalwelfarefurness.org.uk'),
  ('Ashbourne & District Animal Welfare Society', 'Full', 'East Midlands', 'www.ashbourneanimalwelfare.org'),
  ('Band of Rescuers North Yorkshire', 'Full', 'Yorkshire & The Humber', 'www.bandofrescuers.co.uk'),
  ('Clare Animal Welfare CLG', 'Provisional', 'Ireland', 'www.clareanimalwelfare.ie'),
  ('Greyhound Trust - National Greyhound Centre', 'Full', 'South East England', 'www.greyhoundtrust.org.uk'),
  ('Guernsey SPCA', 'Full', 'Channel Islands', 'www.gspca.org.gg'),
  ('Jersey SPCA Animals'' Shelter', 'Full', 'Channel Islands', 'www.jspca.org.je'),
  ('Manx SPCA', 'Full', 'Isle of Man', 'www.manxspca.com'),
  ('Mayo SPCA', 'Provisional', 'Ireland', 'www.mayospca.ie'),
  ('Pawprints Dog Rescue', 'Full', 'West Midlands', 'www.pawprintsdogrescue.org'),
  ('PAWS Animal Rescue', 'Full', 'Ireland', 'www.paws.ie'),
  ('People for Animal Care Trust (PACT)', 'Full', 'East England', 'www.pactsanctuary.org'),
  ('Phoenix French Bulldog Rescue', 'Full', 'East England', 'www.phoenixfrenchbulldogrescue.org'),
  ('Pro Dogs Direct', 'Full', 'South East England', 'www.prodogsdirect.org.uk'),
  ('Rain Rescue', 'Full', 'Yorkshire & The Humber', 'www.rainrescue.co.uk'),
  ('Rainbow Rescue', 'Full', 'Northern Ireland', 'www.rainbowrehoming.com'),
  ('Raystede Centre for Animal Welfare', 'Full', 'South East England', 'www.raystede.org'),
  ('Rescue Me Animal Sanctuary', 'Full', 'North West England', 'www.rescueme.org.uk'),
  ('Rosie''s Trust', 'Full', 'Northern Ireland', 'www.rosiestrust.org'),
  ('Rottweiler Welfare Association', 'Full', 'West Midlands', 'www.rottweilerwelfare.co.uk'),
  ('RSPCA', 'Full', 'National', 'www.rspca.org.uk'),
  ('RSPCA Brighton & The Heart of Sussex', 'Full', 'South East England', 'www.rspca-brighton.org.uk'),
  ('RSPCA Canterbury and District Branch', 'Full', 'South East England', 'www.rspca.org.uk/local/canterbury-and-district-branch'),
  ('RSPCA Chesterfield and North Derbyshire Branch', 'Full', 'South East', 'www.chesterfield-rspca.org.uk'),
  ('RSPCA Cornwall', 'Full', 'South West England', 'www.rspcacornwall.org.uk'),
  ('RSPCA Coventry and District Branch', 'Full', 'West Midlands', 'www.rspca-coventryanddistrict.org.uk'),
  ('RSPCA Kent Isle of Thanet Branch', 'Full', 'South East England', 'www.rspcathanet.org.uk'),
  ('RSPCA Lancashire East Branch', 'Full', 'North West England', 'www.rspca-lancseast.org.uk'),
  ('RSPCA Little Valley', 'Full', 'South West England', 'www.rspca-littlevalley.org.uk'),
  ('RSPCA Leeds, Wakefield & District Branch', 'Full', 'Yorkshire & The Humber', 'www.rspcaleedsandwakefield.org.uk'),
  ('RSPCA Leicester/Woodside Animal Centre', 'Full', 'East Midlands', 'www.rspcaleicester.org.uk'),
  ('RSPCA Llys Nini Branch', 'Full', 'South West Wales', 'www.rspca-llysnini.org.uk'),
  ('RSPCA Norwich', 'Full', 'East England', 'www.rspcanorwich.org.uk'),
  ('RSPCA Radcliffe Animal Shelter Trust', 'Full', 'East Midlands', 'www.rspca-radcliffe.org.uk'),
  ('RSPCA Sheffield Branch', 'Full', 'Yorkshire & The Humber', 'www.rspcasheffield.org'),
  ('RSPCA Southport, Ormskirk & District Branch', 'Full', 'North West England', 'www.rspcasouthport.org'),
  ('RSPCA Sussex East and Hastings Branch', 'Full', 'East Midlands', 'www.bluebellridge.org'),
  ('RSPCA Warrington, Halton and St Helens Branch', 'Full', 'North West England', 'www.rspca-whs.org.uk'),
  ('RSPCA Westmorland Branch', 'Full', 'North West England', 'www.rspca-westmorland.org.uk'),
  ('Saints Sled Dog Rescue', 'Full', 'National', 'www.saintssleddogrescue.co.uk'),
  ('Saving Saints Rescue UK', 'Full', 'North West England', 'www.savingsaintsrescue.co.uk'),
  ('Scottish Staffordshire Bull Terrier Rescue', 'Full', 'Aberdeen & Grampian', 'www.staffierescuescotland.co.uk'),
  ('Second Chance Akita Rescue', 'Full', 'West Midlands', 'www.secondchanceakitarescue.co.uk'),
  ('Senior Staffy Club', 'Full', 'West Midlands', 'www.seniorstaffyclub.co.uk'),
  ('Society for Abandoned Animals', 'Full', 'North West England', 'www.saarescue.co.uk'),
  ('Southern Golden Retriever Rescue', 'Full', 'South England', 'www.sgrr.org.uk'),
  ('Spaniel Aid CIO', 'Full', 'National', 'www.spanielaid.co.uk'),
  ('Spirit of the Dog Rescue', 'Full', 'East England', 'www.spiritofthedog.org.uk'),
  ('Sprocker Assist and Rescue', 'Full', 'National', 'www.sprockerassist.org'),
  ('St Francis Dogs Home', 'Full', 'South West England', 'www.stfrancisnewquay.org.uk'),
  ('Staffie and Stray Rescue', 'Full', 'South West England', 'www.staffieandstrayrescue.co.uk'),
  ('Stokenchurch Dog Rescue', 'Full', 'South East England', 'www.stokenchurchdogrescue.org.uk'),
  ('Tails Animal Welfare', 'Full', 'North West England', 'www.tailsanimalwelfare.com'),
  ('Team Poundie', 'Full', 'North East England', 'www.teampoundie.com'),
  ('Teckels Animal Sanctuaries', 'Full', 'South West England', 'www.teckelsanimalsanctuaries.co.uk'),
  ('The Animal House Rescue', 'Full', 'West Midlands', 'www.theanimalhouserescue.co.uk'),
  ('The Cat Welfare Group', 'Full', 'South East England', 'www.thecatwelfaregroup.org'),
  ('The Friends of Assisi Animal Sanctuary', 'Full', 'Northern Ireland', 'www.assisi-ni.org'),
  ('The Mutts Nutts Rescue', 'Full', 'East Midlands', 'www.themuttsnuttsrescue.org'),
  ('The Kennel Club', 'Full', 'London', 'www.thekennelclub.org.uk'),
  ('Thornberry Animal Sanctuary', 'Full', 'Yorkshire & The Humber', 'www.thornberryanimalsanctuary.org'),
  ('Three Counties Dog Rescue', 'Full', 'East Midlands', 'www.threecountiesdogrescue.org'),
  ('UK Spaniel Rescue', 'Full', 'National', 'www.ukspanielrescue.co.uk'),
  ('USPCA', 'Full', 'Northern Ireland', 'www.uspca.co.uk'),
  ('Wadars Animal Rescue', 'Full', 'South East England', 'www.wadars.co.uk'),
  ('Warrington Animal Welfare', 'Full', 'North West England', 'www.warringtonanimalwelfare.org.uk'),
  ('West Yorkshire Dog Rescue', 'Full', 'Yorkshire & The Humber', 'www.westyorkshiredogrescue.co.uk'),
  ('Wirral Animal Welfare Association', 'Full', 'North West England', 'www.wirralanimalwelfare.com'),
  ('Woodlands Animal Sanctuary', 'Full', 'North West England', 'www.woodlandsanimalsanctuary.org.uk'),
  ('Worcestershire Animal Rescue Shelter', 'Full', 'West Midlands', 'www.wars.org.uk'),
  ('Wythall Animal Sanctuary', 'Full', 'West Midlands', 'www.wythallanimalsanctuary.org')
ON CONFLICT (name) DO NOTHING;
