-- Add bare/partial breed-word synonyms commonly produced by rescue site
-- scrapers after stripping "cross"/"mix"/"type" suffixes.
--
-- When Cardiff Dogs Home pages say "Terrier cross" or "Spaniel mix", the
-- parser strips the suffix leaving just "Terrier" or "Spaniel" — which
-- didn't match any breed and fell back to "Crossbreed".  These synonyms
-- map those bare words to the most likely canonical breed.

INSERT INTO dogadopt.breed_synonyms (synonym, canonical_breed_name) VALUES
  -- Bare group words → most common UK breed in that group
  ('Terrier', 'Terrier Mix'),
  ('Spaniel', 'Cocker Spaniel'),
  ('Collie', 'Border Collie'),
  ('Shepherd', 'German Shepherd'),
  ('Retriever', 'Labrador Retriever'),
  ('Hound', 'Greyhound'),
  ('Pointer', 'Pointer'),
  ('Setter', 'Irish Setter'),
  ('Mastiff', 'Mastiff'),
  ('Bulldog', 'Bulldog'),
  ('Sheepdog', 'Old English Sheepdog'),
  ('Pinscher', 'Doberman Pinscher'),

  -- Common short-form breed names from rescue listings
  ('Akita Inu', 'Akita'),
  ('Bull Mastiff', 'Bullmastiff'),
  ('Pit Bull', 'American Pit Bull Terrier'),
  ('Pitbull', 'American Pit Bull Terrier'),
  ('APBT', 'American Pit Bull Terrier'),
  ('American Bulldog', 'American Bulldog'),
  ('Lurcher Type', 'Lurcher'),
  ('Greyhound Type', 'Greyhound'),
  ('Whippet Type', 'Whippet'),
  ('Collie Type', 'Border Collie'),
  ('Terrier Type', 'Terrier Mix'),
  ('Spaniel Type', 'Cocker Spaniel'),
  ('Shepherd Type', 'German Shepherd'),
  ('Hound Type', 'Greyhound'),
  ('Husky Type', 'Siberian Husky'),
  ('Mastiff Type', 'Mastiff'),
  ('Bulldog Type', 'Bulldog'),
  ('Bull Terrier Type', 'Bull Terrier'),
  ('Rottweiler Type', 'Rottweiler'),

  -- Size-qualified variants that rescue sites use
  ('Small Terrier', 'Terrier Mix'),
  ('Large Terrier', 'Terrier Mix'),
  ('Small Spaniel', 'Cocker Spaniel'),

  -- "X breed" patterns (cleanBreedNames strips "breed" but not always)
  ('Staffie Bull', 'Staffordshire Bull Terrier'),
  ('Staffy Bull', 'Staffordshire Bull Terrier'),
  ('Staff Bull', 'Staffordshire Bull Terrier'),
  ('Staffie Bull Terrier', 'Staffordshire Bull Terrier'),

  -- Additional UK rescue-common informal names missing from first migration
  ('German Shep', 'German Shepherd'),
  ('German Sheppard', 'German Shepherd'),
  ('German Shephard', 'German Shepherd'),
  ('Rottweiller', 'Rottweiler'),
  ('Rotweiler', 'Rottweiler'),
  ('Boarder Collie', 'Border Collie'),
  ('Boarder', 'Border Collie'),
  ('Bullmastif', 'Bullmastiff'),
  ('Dalmation', 'Dalmatian'),
  ('Pomerian', 'Pomeranian'),
  ('Pomerainan', 'Pomeranian'),
  ('Shitzu', 'Shih Tzu'),
  ('Shih-tsu', 'Shih Tzu'),
  ('Shi Tzu', 'Shih Tzu'),
  ('Chihuaha', 'Chihuahua'),
  ('Chiwawa', 'Chihuahua'),
  ('Chiuahua', 'Chihuahua'),
  ('Bichon Frisé', 'Bichon Frise'),
  ('Bishon', 'Bichon Frise'),
  ('Bishon Frise', 'Bichon Frise'),
  ('Weimeraner', 'Weimaraner'),
  ('Weimraner', 'Weimaraner'),
  ('Yorkshire', 'Yorkshire Terrier'),
  ('Yorky', 'Yorkshire Terrier'),
  ('Lhaso Apso', 'Lhasa Apso'),
  ('Llasa Apso', 'Lhasa Apso'),
  ('Lhasa Apsa', 'Lhasa Apso'),
  ('King Charles Cavalier', 'Cavalier King Charles Spaniel'),
  ('CKCS', 'Cavalier King Charles Spaniel'),
  ('Cav', 'Cavalier King Charles Spaniel'),
  ('Cavalier Spaniel', 'Cavalier King Charles Spaniel'),
  ('Sheltie', 'Shetland Sheepdog'),
  ('Shetland', 'Shetland Sheepdog'),
  ('Bearded', 'Bearded Collie'),
  ('Beardie', 'Bearded Collie'),
  ('Wirehaired', 'Wire Fox Terrier'),
  ('Wire Haired Fox Terrier', 'Fox Terrier (Wire)'),
  ('Mini Pin', 'Miniature Pinscher'),
  ('MinPin', 'Miniature Pinscher'),
  ('Old English', 'Old English Sheepdog'),
  ('Deerhound', 'Scottish Deerhound'),
  ('Wolfhound', 'Irish Wolfhound'),
  ('Foxhound', 'English Foxhound'),
  ('Water Spaniel', 'Irish Water Spaniel'),
  ('Cocker Cross', 'Cocker Spaniel'),
  ('Springer Cross', 'English Springer Spaniel'),
  ('Lab Cross', 'Labrador Retriever'),
  ('Collie Cross', 'Border Collie'),
  ('Husky Cross', 'Siberian Husky'),
  ('GSD Cross', 'German Shepherd'),
  ('Lurcher Cross', 'Lurcher'),
  ('Greyhound Cross', 'Greyhound'),
  ('Whippet Cross', 'Whippet'),
  ('Staffie Cross', 'Staffordshire Bull Terrier'),
  ('Staffie X', 'Staffordshire Bull Terrier'),
  ('Staffy Cross', 'Staffordshire Bull Terrier'),
  ('Staffy X', 'Staffordshire Bull Terrier'),
  ('Lab X', 'Labrador Retriever'),
  ('Collie X', 'Border Collie'),
  ('Husky X', 'Siberian Husky'),
  ('GSD X', 'German Shepherd'),
  ('Poodle Cross', 'Poodle (Standard)'),
  ('Poodle X', 'Poodle (Standard)')
ON CONFLICT (synonym) DO NOTHING;
